version : '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tyjnbr888
      POSTGRES_DB: lms_db
    ports:
      - '5433:5432'

  app:
    env_file:
      - .env
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    depends_on:
      - db
