version : '3.9'

services:
  redis:
    image: redis
    ports: 
      - '6380:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tyjnbr888
      - POSTGRES_DB=lms_db
      - PG_DATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - '5433:5432'

  app:
    env_file:
      - .env
    build: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      - '8001:8000'
    depends_on:
      - db

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app
  
  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data:
