# Generated by Django 4.2.7 on 2023-11-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='payment date')),
                ('paid_object', models.CharField(max_length=255, verbose_name='paid object')),
                ('amount', models.PositiveIntegerField(verbose_name='payment amount')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод денег')], max_length=20, verbose_name='payment method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
