# Generated by Django 4.2.7 on 2023-11-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_remove_payment_paid_object_payment_paid_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, null=True, verbose_name='link to payment'),
        ),
    ]
